"""Generate the revision-r5 part-2 supplement tables (lock v10, FDC-DP) from result files (read-only on the results).

Outputs (writing/supplement/r5b_tables/):
  v10_eps_rule.tex   development epsilon-selection trace (v2 dev, seeds 950-999) from
                     exp/results/pilots/fdc_dp_v2/analysis.json
  v10_ratios.tex     every lock-v10 paired comparison (ratio, 95% CI, UB95, faster/tied/slower) from
                     exp/results/full/v10_analysis_{A,B,D}.json
  v10_methods.tex    per-method lock-v10 rows: geometric-mean N80_pen, N80/tau, share N80 < tau, false streams,
                     exhaustion fractions at N80 (all / control / treatment), runtime, B&B calls, branch-only
                     certificates and node-cap hits
Usage (repo root): .venv/bin/python3 iter_001/writing/scripts/gen_r5b_supp_tables.py
"""
import json
from pathlib import Path

IT = Path(__file__).resolve().parents[2]
FULL = IT / "exp/results/full"
DEV = IT / "exp/results/pilots/fdc_dp_v2/analysis.json"
OUT = IT / "writing/supplement/r5b_tables"
CELLS = [("A", "v10a_full_s16", "X5", 16, "A"), ("A", "v10a_full_s32", "X5", 32, "A"),
         ("B", "v10b_full_s16", "Lenta", 16, "B"), ("B", "v10b_full_s32", "Lenta", 32, "B"),
         ("B", "v10b_full_s64", "Lenta", 64, "B"), ("D", "v10d_full_x5s64", "X5", 64, "D (descr.)")]
DEV_CELLS = [("x5_16", "X5", 16), ("x5_32", "X5", 32), ("x5_64", "X5", 64),
             ("lenta16", "Lenta", 16), ("lenta32", "Lenta", 32), ("lenta64", "Lenta", 64)]
COMPS = [("TU-FDC-DP(b)/RECT-BF-DP-TU", "TU-FDC-DP / RECT-BF-DP-TU (primary)"),
         ("TU-FDC-DP(b)/HC-WoR-DP", "TU-FDC-DP / HC-WoR-DP (descr.)"),
         ("TU-FDC-DP(b)/FDC-DP(a)", "scheme (b) / scheme (a)"),
         ("RECT-BF-DP-TU/HC-WoR-DP", "RECT-BF-DP-TU / HC-WoR-DP")]
METHODS = [("TU-FDC-DP(b)", "TU-FDC-DP(b)"), ("FDC-DP(a)", "FDC-DP(a)"), ("RECT-BF-DP-TU", "RECT-BF-DP-TU"),
           ("HC-WoR-DP", "HC-WoR-DP")]
HDR = "% generated by writing/scripts/gen_r5b_supp_tables.py from {src}; do not edit by hand\n"


def load():
    return {b: json.load(open(FULL / f"v10_analysis_{b}.json")) for b in "ABD"}


def pct(x):
    return f"{100 * x:.1f}"


def ratios_table(an):
    rows = []
    for blk, task, log, S, lab in CELLS:
        c = an[blk]["cells"][task]
        first = True
        for key, name in COMPS:
            v = c["comparisons"][key]
            lead = f"{log}, $S={S}$, $\\eps={c['eps']:g}$, {lab}" if first else ""
            first = False
            rows.append(f"{lead} & {name} & {v['geomean_ratio']:.3f} [{v['ci95_two_sided'][0]:.3f}, "
                        f"{v['ci95_two_sided'][1]:.3f}] & {v['ub95_one_sided']:.3f} & "
                        f"{pct(v['frac_faster'])} / {pct(v['frac_tied'])} / {pct(v['frac_slower'])} & "
                        f"{v['sd_log_ratio']:.3f} \\\\")
        rows.append("\\midrule")
    rows = rows[:-1]
    body = "\n".join(rows)
    return (HDR.format(src="exp/results/full/v10_analysis_{A,B,D}.json") +
            "\\begin{table*}[t]\n\\caption{\\textbf{Lock v10: every paired comparison} (200 fresh streams per cell; "
            "paired geometric-mean $\\Npen$ ratio, two-sided 95\\% percentile-bootstrap CI and one-sided UB95, "
            "$B = 10^4$, seed 42). F / T / S: \\% of streams on which the first method stops earlier / at the same "
            "checkpoint / later. sd: standard deviation of the per-stream log ratio (0 = a constant observed ratio; "
            "for the Lenta $S = 64$ primary row every stream certifies at the same checkpoint pair, checkpoint "
            "quantisation, whereas for (a) vs (b) it means that the two schemes agree within each stream). Blocks A and B are confirmatory (threshold UB95 $< 0.80$ for "
            "the primary row); D and every non-primary row are descriptive.}\n\\label{tab:v10ratios}\n\\small\n"
            "\\begin{tabular}{@{}llllll@{}}\n\\toprule\nCell & Comparison & Ratio [95\\% CI] & UB95 & F / T / S "
            "& sd \\\\\n\\midrule\n" + body + "\n\\bottomrule\n\\end{tabular}\n\\end{table*}\n")


def methods_table(an):
    rows = []
    for blk, task, log, S, lab in CELLS:
        c = an[blk]["cells"][task]
        first = True
        for key, name in METHODS:
            m = c["methods"][key]
            e = m["exhaustion_at_k80_mean"]
            lead = f"{log}, $S={S}$, {lab}" if first else ""
            first = False
            bnb = "---" if m.get("bnb_calls") in (None, 0) else f"{m['bnb_calls']:,}"
            bo = "---" if m.get("bnb_calls") in (None, 0) else f"{m['b_only_certs']}"
            cap = "---" if m.get("bnb_calls") in (None, 0) else f"{m['node_limit_hits']}"
            rows.append(f"{lead} & {name} & {m['geomean_N80_pen']:,.0f} & {m['geomean_N80_over_tau']:.3f} & "
                        f"{pct(m['share_N80_lt_tau'])} & {m['false_streams']} & "
                        f"{e['all']:.3f} / {e['ctrl']:.3f} / {e['treat']:.3f} & "
                        f"{m['sec_cert_per_ck_median']:.2f} / {m['sec_cert_per_ck_max']:.2f} & {bnb} & {bo} & {cap} \\\\")
        rows.append("\\midrule")
    rows = rows[:-1]
    return (HDR.format(src="exp/results/full/v10_analysis_{A,B,D}.json") +
            "\\begin{table*}[t]\n\\caption{\\textbf{Lock v10: per-method rows.} $\\Npen$: geometric mean over 200 "
            "streams ($\\tau_R$ = 100,393 on X5 and 343,513 on Lenta). $<\\tau_R$: \\% of streams reaching 12 of 15 "
            "before $\\tau_R$. False: streams with any false certificate over the whole run to 15 of 15. Exhausted at "
            "$N_{80}$: mean fraction of all / control / treatment cells whose pool is empty at the method's $N_{80}$ "
            "checkpoint. Seconds: median / maximum certification time per checkpoint for all 15 problems (Python)"
            ". B\\&B: scheme-(b) calls (made only when scheme (a) fails), certificates found only by "
            "scheme (b), and node-cap ($2\\cdot 10^5$) hits.}\n\\label{tab:v10methods}\n\\footnotesize\n"
            "\\setlength{\\tabcolsep}{3pt}\n\\begin{tabular}{@{}llrrrrlllll@{}}\n\\toprule\nCell & Method & $\\Npen$ & "
            "$N_{80}/\\tau_R$ & $<\\tau_R$ & False & Exhausted at $N_{80}$ & Seconds & B\\&B & (b) only & Cap \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table*}\n")


def eps_table():
    d = json.load(open(DEV))
    rows = []
    for key, log, S in DEV_CELLS:
        r = d["eps_rule"][key]
        trace = "; ".join(f"{t['eps']:g}: {t['per_rect']['RECT-BF-DP']['successes']} / "
                          f"{t['per_rect']['HC-WoR-DP']['successes']}" for t in r["trace"])
        rc = d["rule_selected_cells"][key]
        if r["selected_eps"] is None:
            sel, rat = "none (descriptive)", "---"
        else:
            sel, rat = f"{r['selected_eps']:g}", f"{rc['ratio']:.3f} ({rc['ub95']:.3f})"
        rows.append(f"{log}, {S} & {trace} & {sel} & {rat} \\\\")
    return (HDR.format(src="exp/results/pilots/fdc_dp_v2/analysis.json") +
            "\\begin{table}[H]\n\\caption{\\textbf{Development $\\eps$ selection} (v2 development code, seeds "
            "950--999, development halves). Trace: $\\eps$ on the declared grid: streams of 50 on which RECT-BF-DP / "
            "HC-WoR-DP reach 12 of 15 strictly before $\\tau_R$. The rule takes the smallest $\\eps$ at which the "
            "better of the two reaches at least 40; it never reads FDC-DP. Last column: FDC-DP(b) / RECT-BF-DP, "
            "paired geometric-mean $\\Npen$ ratio (UB95) at the selected $\\eps$ (not evidence).}\n"
            "\\label{tab:v10eps}\n\\footnotesize\n\\setlength{\\tabcolsep}{3pt}\n"
            "\\begin{tabular}{@{}l>{\\raggedright\\arraybackslash}p{3.2cm}ll@{}}\n\\toprule\nLog, $S$ & Trace & "
            "Selected & Dev ratio (UB95) \\\\\n\\midrule\n" + "\n".join(rows) +
            "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


def main():
    OUT.mkdir(exist_ok=True)
    an = load()
    (OUT / "v10_ratios.tex").write_text(ratios_table(an))
    (OUT / "v10_methods.tex").write_text(methods_table(an))
    (OUT / "v10_eps_rule.tex").write_text(eps_table())
    print("wrote", sorted(p.name for p in OUT.glob("*.tex")))


if __name__ == "__main__":
    main()
