"""Generate the supplement tables added in paper revision r4 directly from result files (no hand transcription).

Writes writing/supplement/r4_tables/{ablation,hillstrom,sensitivity,regime,v9_confirm,v9_hillstrom}.tex.
  ablation.tex     FDC-HG / FDC-LOC / ORACLE-LOC and the dense-monitoring block
                   (exp/results/pilots/{fdc_hg,v9_candidates}/analysis_dev.json)
  hillstrom.tex    Hillstrom design B development block (exp/results/pilots/hillstrom_v9/summary_b.json)
  sensitivity.tex  copy of exp/results/full/v8_posthoc_E/table.tex (generated by run_v8_posthoc_E.py)
  regime.tex       exp/results/full/v8_posthoc_F/table.tex as a two-column table* (generated by run_v8_posthoc_F.py)
  v9_confirm.tex   lock-v9 blocks A (Criteo) and B (X5), every registered row on both grids
                   (exp/results/full/v9_analysis_{A,B}.json; added in r4 part 2)
  v9_hillstrom.tex lock-v9 block C, Hillstrom evaluation half, designs B and A (exp/results/full/v9_analysis_C.json)
Usage (repo root): .venv/bin/python3 iter_001/writing/scripts/gen_r4_supp_tables.py
"""
import json
from pathlib import Path

IT = Path(__file__).resolve().parents[2]
RES = IT / "exp/results"
OUT = IT / "writing/supplement/r4_tables"


def f3(x):
    return f"{x:.3f}"


def cell(r):
    return f"{f3(r['geomean_ratio'])} ({f3(r['ub95_one_sided'])})"


def ablation():
    hg = json.load(open(RES / "pilots/fdc_hg/analysis_dev.json"))
    vc = json.load(open(RES / "pilots/v9_candidates/analysis_dev.json"))
    hgb = [hg["cr9"][0]] + sorted(hg["x5"], key=lambda b: b["eps"])
    vcb = [vc["cr9"][0]] + sorted(vc["x5"], key=lambda b: b["eps"])
    rows = [("FDC-HG / FDC-BF", hgb, "FDC-HG/FDC-BF"), ("FDC-LOC / FDC-BF", vcb, "FDC-LOC/FDC-BF"),
            ("ORACLE-LOC / FDC-BF (invalid)", vcb, "ORACLE-LOC/FDC-BF"),
            ("FDC-HG / RECT-ck-HG*", hgb, "FDC-HG/RECT-ck-HG"), ("FDC-LOC / RECT-ck-HG*", vcb, "FDC-LOC/RECT-ck-HG"),
            ("FDC-BF / HC-WoR*", vcb, "FDC-BF/HC-WoR")]
    L = [r"% generated by writing/scripts/gen_r4_supp_tables.py -- do not edit by hand",
         r"\begin{table*}[t]",
         r"\caption{\textbf{Ablations and the time-uniform block} (post hoc, development halves, seeds 950--999, 50 paired streams; ratio of $\Npen$ geometric means with one-sided UB95 in parentheses; $<1$: the first method reads fewer rows). FDC-HG replaces the Bennett cell bound by the upper envelope of the exact hypergeometric log-MGF over the variance box; FDC-LOC replaces $\beta_J$ by a gap-weighted localised exponent; ORACLE-LOC uses the true gaps and is invalid (a ceiling only). Both upgrades are valid, never wider than FDC-BF, and had 0 false streams; neither met its pre-stated go criterion (UB95 $<$ 0.90 on one log). Lower panel: dense monitoring at 77 evaluation times; TU-FDC[K20] is FDC-BF certifying at every time with the width of the last of its 20 checkpoints (Remark 4.2); FDC-BF[K77] refreshes widths at all 77 times and pays $\ln(77/20)$ in the exponent.}",
         r"\label{tab:ablation}", r"\small", r"\begin{tabular}{@{}lllll@{}}", r"\toprule",
         r"Ratio & CR9, $\eps = 0.001$ & X5, $\eps = 0.015$ & X5, $\eps = 0.02$ & X5, $\eps = 0.03$ \\", r"\midrule"]
    for name, blocks, key in rows:
        L.append(name + " & " + " & ".join(cell(b["ratios"][key]) for b in blocks) + r" \\")
    L += [r"\midrule", r"\multicolumn{5}{@{}l}{\emph{Dense monitoring (77 evaluation times; CR9 $\eps = 0.001$, X5 $\eps = 0.02$)}} \\"]
    crd, x5d = vc["cr9d"][0]["ratios"], vc["x5d"][0]["ratios"]
    for key, name in [("TU-FDC[K20]/HC-WoR", "TU-FDC[K20] / HC-WoR* (dense)"),
                      ("FDC-BF[K77]/HC-WoR", "FDC-BF[K77] / HC-WoR* (dense)"),
                      ("TU-FDC[K20]/RECT-ck-HG", "TU-FDC[K20] / RECT-ck-HG* ($K = 77$ ledger)"),
                      ("TU-FDC[K20]/FDC-BF[K77]", "TU-FDC[K20] / FDC-BF[K77]"),
                      ("TU-FDC[K20]/FDC-BF@K20", "TU-FDC dense / FDC-BF on 20 checkpoints"),
                      ("HC-WoR/HC-WoR@K20", "HC-WoR* dense / HC-WoR* on 20 checkpoints")]:
        L.append(name + f" & {cell(crd[key])} & --- & {cell(x5d[key])} & --- \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    return "\n".join(L) + "\n"


def hillstrom():
    h = json.load(open(RES / "pilots/hillstrom_v9/summary_b.json"))
    eps = ["0.01", "0.0125", "0.015"]
    names = [("RECT-ck-HG[0.2]", "RECT-ck-HG* (control share 0.2)"), ("HC-WoR{nstar,0.75,1}[0.2]", "HC-WoR* (control share 0.2)"),
             ("PJC-BF[local,b=4,neyman]", "PJC-local* (one boundary, Neyman)"), ("RECT-ck-BF", "RECT-ck-BF (matched)"),
             ("RECT-ck-HG[bal]", "RECT-ck-HG, 1/3 split (untuned)"), ("FDC-BF[ney]", "FDC-BF, frozen Neyman (descr.)")]
    L = [r"% generated by writing/scripts/gen_r4_supp_tables.py -- do not edit by hand",
         r"\begin{table*}[t]",
         r"\caption{\textbf{Hillstrom, three arms, design B} (descriptive; development half, 32,119 rows; seeds 950--999, 50 paired streams; CZ6 segmentation, 729 policies, visit outcome, e-mail costs $(0, 1, 0.5)$). FDC-BF / method paired geometric-mean ratio of $\Npen$ [95\% CI] (UB95); $\Npen/\tau_R$ of FDC-BF; share of the rival's streams that reach 12/15 only at $\tau_R$; and the width ratio at the last checkpoint before $\tau_R$ (12th-smallest running-minimum $U$, $\eps = 0.0125$), which is free of the $\tau_R$ censoring. Rivals tuned on development seeds 900--949 at $\eps = 0.0125$. All methods: 0/50 false streams at every $\eps$.}",
         r"\label{tab:hillstrom}", r"\footnotesize", r"\setlength{\tabcolsep}{3pt}", r"\begin{tabular}{@{}llllll@{}}", r"\toprule",
         r"Rival & $\eps = 0.01$ & $\eps = 0.0125$ (design $\eps$) & $\eps = 0.015$ & at $\tau_R$ (0.0125) & width ratio \\", r"\midrule"]
    for k, nm in names:
        cells = []
        for e in eps:
            r = h["by_eps"][e]["ratios_FDC_BF_over"][k]
            cells.append(f"{f3(r['ratio'])} [{f3(r['lo95'])}, {f3(r['hi95'])}] ({f3(r['ub95_one_sided'])})")
        at = h["by_eps"]["0.0125"]["methods"][k]["share_at_tau"]
        u = h["by_eps"]["0.0125"]["u12_ratio_FDC_BF_over"][k]["ratio"]
        L.append(nm + " & " + " & ".join(cells) + f" & {100 * at:.0f}\\% & {f3(u)} \\\\")
    fb = [h["by_eps"][e]["methods"]["FDC-BF"]["geomean_N80_over_tau"] for e in eps]
    L += [r"\midrule", "FDC-BF $\\Npen/\\tau_R$ & " + " & ".join(f3(x) for x in fb) + r" & 0\% & --- \\",
          r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    return "\n".join(L) + "\n"


def sensitivity():
    return (r"% copied by writing/scripts/gen_r4_supp_tables.py from exp/results/full/v8_posthoc_E/table.tex" + "\n"
            + open(RES / "full/v8_posthoc_E/table.tex").read())


def regime():
    t = open(RES / "full/v8_posthoc_F/table.tex").read()
    t = t.replace(r"\begin{table}[t]", r"\begin{table*}[t]").replace(r"\end{table}", r"\end{table*}")
    return r"% adapted (table -> table*) by writing/scripts/gen_r4_supp_tables.py from exp/results/full/v8_posthoc_F/table.tex" + "\n" + t


def ci_cell(r):
    lo, hi = r["ci95_two_sided"]
    return f"{f3(r['geomean_ratio'])} [{f3(lo)}, {f3(hi)}] ({f3(r['ub95_one_sided'])})"


def fts(r):
    def p(x):
        v = round(100 * x, 1)
        return f"{v:g}"
    return f"{p(r['frac_faster'])} / {p(r['frac_tied'])} / {p(r['frac_slower'])}"


def v9_confirm():
    A = json.load(open(RES / "full/v9_analysis_A.json"))
    B = json.load(open(RES / "full/v9_analysis_B.json"))
    dense = [("HC-WoR@D", "HC-WoR* (primary)"), ("RECT-ck-BF-TU@D", "RECT-ck-BF-TU (primary)"),
             ("PJC-local@D", "PJC-local*, 77-time ledger (NI in X5)"), ("TU-PJC@D", "TU-PJC (NI in X5)"),
             ("RECT-ck-HG@D", "RECT-ck-HG*, 77-time ledger"), ("FDC-BF[K77]@D", "FDC-BF[K77], fresh widths"),
             ("TU-LOC@D", "TU-LOC"), ("FDC-BF@K", "FDC-BF on the 20 checkpoints")]
    grid = [("HC-WoR@K", "HC-WoR*"), ("RECT-ck-HG@K", "RECT-ck-HG*"), ("RECT-ck-BF@K", "RECT-ck-BF"),
            ("RECT-ck-BF+box@K", "RECT-ck-BF+box"), ("PJC-local@K", "PJC-local*"),
            ("FDC-MR[front3]@K", "FDC-MR[front3]"), ("FDC-HG@K", "FDC-HG (no-go)"), ("FDC-LOC@K", "FDC-LOC (no-go)")]
    L = [r"% generated by writing/scripts/gen_r4_supp_tables.py -- do not edit by hand",
         r"\begin{table*}[t]",
         r"\caption{\textbf{Lock v9, blocks A (Criteo CR9, seeds 37000--37199, $\eps = 0.001$) and B (X5 X9 evaluation half, seeds 37200--37399, $\eps = 0.02$)}: every registered row, 200 paired streams per block. Upper panel: every method monitored at the same 77 times; ratio = TU-FDC / method, paired geometric mean of $\Npen$ with 95\% CI and one-sided UB95 in parentheses; F/T/S = \% of streams on which TU-FDC stops earlier / at the same time / later. Lower panel: the 20-checkpoint grid, ratio = FDC-BF / method. "
         + f"Verdicts: A {A['decision']['verdict'].replace('_', ' ')} (governing UB95 {f3(A['decision']['UB_star'])}, threshold 0.85); "
         + f"B {B['decision']['verdict'].replace('_', ' ')} (governing UB95 {f3(B['decision']['UB_star'])}, threshold 0.50; non-inferiority UB95 {f3(B['decision']['UB_star_NI'])}, margin 1.05). "
         + f"False streams: {A['all_rigorous_false_streams_total']} (A) and {B['all_rigorous_false_streams_total']} (B) over all rigorous methods; replicas (R1, R2, R2b, R2c): {A['replica_status_combined']['status']} / {B['replica_status_combined']['status']}." + "}",
         r"\label{tab:v9}", r"\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{@{}lllll@{}}", r"\toprule",
         r"Method & Criteo: ratio [95\% CI] (UB95) & F / T / S & X5: ratio [95\% CI] (UB95) & F / T / S \\", r"\midrule",
         r"\multicolumn{5}{@{}l}{\emph{77 monitoring times: TU-FDC / method}} \\"]
    ca, cb = A["comparisons"]["TU-FDC@D|N80_pen"], B["comparisons"]["TU-FDC@D|N80_pen"]
    for k, name in dense:
        L.append(f"{name} & {ci_cell(ca[k])} & {fts(ca[k])} & {ci_cell(cb[k])} & {fts(cb[k])} \\\\")
    L += [r"\midrule", r"\multicolumn{5}{@{}l}{\emph{20 checkpoints: FDC-BF / method}} \\"]
    ka, kb = A["comparisons"]["FDC-BF@K|N80_pen"], B["comparisons"]["FDC-BF@K|N80_pen"]
    for k, name in grid:
        L.append(f"{name} & {ci_cell(ka[k])} & {fts(ka[k])} & {ci_cell(kb[k])} & {fts(kb[k])} \\\\")
    da, db = A["describe"], B["describe"]
    L += [r"\midrule",
          f"$\\Npen/\\tau_R$: TU-FDC; FDC-BF (20 checkpoints) & {f3(da['TU-FDC@D']['geomean_N80_pen_over_tau'])}; {f3(da['FDC-BF@K']['geomean_N80_pen_over_tau'])} & & "
          f"{f3(db['TU-FDC@D']['geomean_N80_pen_over_tau'])}; {f3(db['FDC-BF@K']['geomean_N80_pen_over_tau'])} & \\\\",
          f"$\\Npen/\\tau_R$: HC-WoR* dense; 20 checkpoints & {f3(da['HC-WoR@D']['geomean_N80_pen_over_tau'])}; {f3(da['HC-WoR@K']['geomean_N80_pen_over_tau'])} & & "
          f"{f3(db['HC-WoR@D']['geomean_N80_pen_over_tau'])}; {f3(db['HC-WoR@K']['geomean_N80_pen_over_tau'])} & \\\\",
          r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]
    return "\n".join(L)


def v9_hillstrom():
    C = json.load(open(RES / "full/v9_analysis_C.json"))
    tb, ta = C["per_task"]["v9c_full_b"], C["per_task"]["v9c_full_a"]
    rows_b = [("RECT-ck-HG[0.2]", "RECT-ck-HG* (control share 0.2)"), ("HC-WoR{nstar,0.75,1}[0.2]", "HC-WoR* (control share 0.2)"),
              ("PJC-BF[local,b=4,neyman]", "PJC-local* (one boundary, Neyman)"), ("RECT-ck-BF", "RECT-ck-BF (matched)"),
              ("RECT-ck-HG[bal]", "RECT-ck-HG, 1/3 split (untuned)"), ("FDC-BF[0.5]", "FDC-BF, control share 0.5"),
              ("FDC-BF[ney]", "FDC-BF, frozen Neyman")]
    epss = ["0.01", "0.0125", "0.015"]
    pe = tb["per_eps"]
    L = [r"% generated by writing/scripts/gen_r4_supp_tables.py -- do not edit by hand",
         r"\begin{table*}[t]",
         r"\caption{\textbf{Hillstrom, lock-v9 block C} (preregistered descriptive reuse; evaluation half, "
         + f"{pe['0.0125']['describe']['FDC-BF']['tau_R']:,}"
         + r" rows; 200 paired streams). Upper panel: design B (CZ6, 729 policies, visit, e-mail costs $(0, 1, 0.5)$, seeds 37400--37599); FDC-BF / method paired geometric-mean $\Npen$ ratio [95\% CI] (UB95); share of the rival's streams that reach 12/15 only at $\tau_R$; ratio of 12th-smallest running-minimum certificate bounds at the last checkpoint before $\tau_R$, over streams where both are finite (eligible / 200). Lower panel: design A (CR6, costs $(0, 1.5, 1)$, seeds 37600--37799) at its design $\eps = 0.0075$. "
         + f"Wording rule: design B {tb['wording']['wording'].replace('_', ' ')}, design A {ta['wording']['wording'].replace('_', ' ')}; "
         + f"every method had 0 false streams; replicas {tb['replica_status']} / {ta['replica_status']}." + "}",
         r"\label{tab:hillstromv9}", r"\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{@{}llllll@{}}", r"\toprule",
         r"Rival & $\eps = 0.01$ & $\eps = 0.0125$ (design $\eps$) & $\eps = 0.015$ & at $\tau_R$ & bound ratio \\", r"\midrule",
         r"\multicolumn{6}{@{}l}{\emph{Design B (main)}} \\"]
    fs_total = 0
    for k, name in rows_b:
        cells = [ci_cell(pe[e]["FDC-BF|N80_pen"][k]) for e in epss]
        share = pe["0.0125"]["describe"][k]["share_N80_at_tau"]
        rb = pe["0.0125"]["running_bound_ratio_k18_FDC-BF_over"][k]
        L.append(f"{name} & {cells[0]} & {cells[1]} & {cells[2]} & {round(100 * share, 1):g}\\% & {f3(rb['ratio'])} ({rb['eligible']}) \\\\")
    for e in epss:
        fs_total += sum(v["false_streams"] for v in pe[e]["false_streams"].values())
    L.append(f"FDC-BF $\\Npen/\\tau_R$ & {f3(pe['0.01']['describe']['FDC-BF']['geomean_N80_pen_over_tau'])} & "
             f"{f3(pe['0.0125']['describe']['FDC-BF']['geomean_N80_pen_over_tau'])} & {f3(pe['0.015']['describe']['FDC-BF']['geomean_N80_pen_over_tau'])} & "
             f"{round(100 * pe["0.0125"]["describe"]["FDC-BF"]["share_N80_at_tau"], 1):g}\\% & --- \\\\")
    L += [r"\midrule", r"\multicolumn{6}{@{}l}{\emph{Design A (supplement), $\eps = 0.0075$}} \\"]
    pa = ta["per_eps"]["0.0075"]
    rows_a = [("RECT-ck-HG[bal]", "RECT-ck-HG* (1/3 split)"), ("HC-WoR{prpl,0.5,-}[bal]", "HC-WoR* (1/3 split)"),
              ("RECT-ck-BF", "RECT-ck-BF (matched)"), ("PJC-BF[local,b=,bal]", "PJC-local* (no reset, 1/3)"),
              ("PJC-BF[local,b=2,neyman]", "PJC (one boundary, Neyman)")]
    for k, name in rows_a:
        r = pa["FDC-BF|N80_pen"][k]
        share = pa["describe"][k]["share_N80_at_tau"]
        rb = pa["running_bound_ratio_k18_FDC-BF_over"][k]
        L.append(f"{name} & & {ci_cell(r)} & & {round(100 * share, 1):g}\\% & {f3(rb['ratio'])} ({rb['eligible']}) \\\\")
    for e in ta["per_eps"]:
        fs_total += sum(v["false_streams"] for v in ta["per_eps"][e]["false_streams"].values())
    L.append(f"FDC-BF $\\Npen/\\tau_R$ & & {f3(pa['describe']['FDC-BF']['geomean_N80_pen_over_tau'])} & & "
             f"{round(100 * pa["describe"]["FDC-BF"]["share_N80_at_tau"], 1):g}\\% & --- \\\\")
    assert fs_total == 0, fs_total
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]
    return "\n".join(L)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, fn in [("ablation", ablation), ("hillstrom", hillstrom), ("sensitivity", sensitivity), ("regime", regime),
                     ("v9_confirm", v9_confirm), ("v9_hillstrom", v9_hillstrom)]:
        (OUT / f"{name}.tex").write_text(fn())
        print("wrote", OUT / f"{name}.tex")


if __name__ == "__main__":
    main()
