"""Supplement tables for block v10-posthoc-G (post hoc, descriptive) from exp/results/full/v10_posthoc_G/summary.json."""
import json
from pathlib import Path

W = Path(__file__).resolve().parents[2]
S = json.loads((W / "exp/results/full/v10_posthoc_G/summary.json").read_text())
OUT = W / "writing/supplement/r6_tables"
OUT.mkdir(exist_ok=True)
HDR = "% generated by writing/scripts/gen_r6_blockG_tables.py from exp/results/full/v10_posthoc_G/summary.json; do not edit by hand\n"
NAME = {"x5": "X5", "lenta": "Lenta"}


def f3(x):
    return f"{x:.3f}"


# ---- G1
L = [HDR, r"\begin{table*}[t]",
     r"\caption{\textbf{Block G1: reads against $\eps$} (post hoc, descriptive; evaluation seeds 38400--38599, the same 200 streams at every $\eps$). "
     r"$N_{80}/\tau$: geometric mean over streams. Ratios are paired geometric-mean $\Npen$ ratios of TU-FDC-DP(b) to the rival with two-sided 95\% "
     r"percentile-bootstrap CIs ($B = 10^4$, seed 42). Cens.: fraction of RECT-BF-DP-TU streams that do not reach 12 of 15 before $\tau_R$ (their $\Npen = \tau_R$; "
     r"rows with Cens.\ above 0.2 are horizon-sensitive endpoint ratios). Pinned: at least 95\% of RECT-BF-DP-TU streams reach 12 of 15 at the same checkpoint. $\star$: the lock-v10 $\eps$. "
     r"No method had a false stream.}",
     r"\label{tab:g1}", r"\small", r"\begin{tabular}{@{}llrrrrlrl@{}}", r"\toprule",
     r"Table & $S$ & $\eps$ & FDC $N_{80}/\tau$ & RECT $N_{80}/\tau$ & Cens. & vs RECT-BF-DP-TU [95\% CI] & vs HC-WoR-DP & Pinned \\", r"\midrule"]
for d in ("x5", "lenta"):
    for s_ in (16, 32, 64):
        g = S["G1"][f"G1-eval-{d}-{s_}"]
        n = g["n"]
        for e in sorted(g["by_eps"], key=float):
            b = g["by_eps"][e]
            m, r = b["methods"], b["ratios"]
            rr = r["FDC/RECT-BF-DP-TU"]
            cens = 1 - m["RECT-BF-DP-TU"]["n80_lt_tau"] / n
            star = r"$^\star$" if b["lock_eps"] else ""
            L.append(f"{NAME[d]} & {s_} & {float(e):g}{star} & {f3(m['TU-FDC-DP(b)']['N80_over_tau'])} & "
                     f"{f3(m['RECT-BF-DP-TU']['N80_over_tau'])} & {cens:.2f} & {f3(rr['geomean_ratio'])} "
                     f"[{f3(rr['ci95_two_sided'][0])}, {f3(rr['ci95_two_sided'][1])}] & "
                     f"{f3(r['FDC/HC-WoR-DP']['geomean_ratio'])} & {'yes' if m['RECT-BF-DP-TU']['pinned'] else 'no'} \\\\")
        L.append(r"\addlinespace")
L[-1] = r"\bottomrule"
L += [r"\end{tabular}", r"\end{table*}", ""]
(OUT / "blockG_g1.tex").write_text("\n".join(L))

# ---- G2
L = [HDR, r"\begin{table}[t]",
     r"\caption{\textbf{Block G2: heterogeneous knapsack costs} (post hoc, descriptive, development halves only; seeds 950--999, 50 streams per $\eps$, six $\eps$ per row; X5 costs simulated, Lenta costs a covariate proxy). "
     r"(b)/(a): range over $\eps$ of the geometric-mean $\Npen$ ratio of branch-and-bound to min--max. B-only: branch-only certification events (problems certified by (b) but not (a)) among 4,500 problem instances (50 streams $\times$ 6 $\eps$ $\times$ 15 problems). "
     r"vs RECT: range of FDC-DP(b)/RECT-BF-DP over the $\eps$ at which RECT-BF-DP reaches 12 of 15 before $\tau_R$ on at least 80\% of streams (--: none). "
     r"Max s: largest certification time per checkpoint. No node-limit hit; no false stream.}",
     r"\label{tab:g2}", r"\small", r"\begin{tabular}{@{}llllrr@{}}", r"\toprule",
     r"Table & $S$ & (b)/(a) & vs RECT & B-only & Max s \\", r"\midrule"]
for d in ("x5", "lenta"):
    for s_ in (16, 32, 64):
        g = S["G2"][f"G2-dev-{d}-{s_}"]
        ba, vr, bo, mx = [], [], 0, 0.0
        for e, b in g["by_eps"].items():
            m, r = b["methods"], b["ratios"]
            ba.append(r["FDC(b)/FDC(a)"]["geomean_ratio"])
            if m["RECT-BF-DP"]["n80_lt_tau"] >= 0.8 * m["RECT-BF-DP"]["n"]:
                vr.append(r["FDC(b)/RECT-BF-DP"]["geomean_ratio"])
            bo += m["FDC-DP(b)"]["b_only_certs"]
            mx = max(mx, m["FDC-DP(b)"]["sec_per_ck_max"])
        vrs = f"{min(vr):.2f}--{max(vr):.2f}" if vr else "--"
        L.append(f"{NAME[d]} & {s_} & {min(ba):.3f}--{max(ba):.3f} & {vrs} & {bo} & {mx:.2f} \\\\")
L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(OUT / "blockG_g2.tex").write_text("\n".join(L))

# ---- G3
L = [HDR, r"\begin{table}[t]",
     r"\caption{\textbf{Block G3: stronger rivals at the lock-v10 cells} (post hoc, descriptive; fresh evaluation seeds 38600--38799, 200 streams per cell). "
     r"Paired geometric-mean $\Npen$ ratio of TU-FDC-DP(b) to each rival, one-sided UB95 in parentheses. RECT-HG-DP: exact-hypergeometric cell radii with the same knapsack worst gap. "
     r"HC-WoR-DP tuned: best of eight configurations on development seeds, selected before any G3 evaluation row. "
     r"Guarantee strength on the 20 checkpoints: RECT-BF-DP-TU TU on the frozen schedule; RECT-HG-DP CP only (a checkpoint-valid exact inversion, "
     r"not a time-uniform rectangle); HC-WoR-DP TU.}",
     r"\label{tab:g3}", r"\small", r"\begin{tabular}{@{}llrlll@{}}", r"\toprule",
     r"Table & $S$ & $\eps$ & RECT-BF-DP-TU & RECT-HG-DP & HC tuned \\", r"\midrule"]
for line in (W / "exp/results/full/v10_posthoc_G/table.tex").read_text().split("% G3")[1].split(r"\midrule")[1].split(r"\bottomrule")[0].strip().splitlines():
    L.append(line)
L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(OUT / "blockG_g3.tex").write_text("\n".join(L))
print("ok", sorted(p.name for p in OUT.iterdir()))
