"""Generate the revision-r5 supplement tables from result files (read-only on the results).

Outputs (writing/supplement/r5_tables/):
  f2_methods.tex  block F2 per-method table, adapted (table -> table*) from exp/results/full/v8_posthoc_F2/table.tex
  f2_h2h.tex      block F2 head-to-head table built from exp/results/full/v8_posthoc_F2/summary.json:
                  frozen pilot-Neyman FDC-BF / adaptive (equal information, J = 1) and charged pilot vs no-pilot
                  adaptive picks (J = 1) with break-even J.
Usage (repo root): .venv/bin/python3 iter_001/writing/scripts/gen_r5_supp_tables.py
"""
import json
from pathlib import Path

IT = Path(__file__).resolve().parents[2]
F2 = IT / "exp/results/full/v8_posthoc_F2"
OUT = IT / "writing/supplement/r5_tables"
ENVS = [("X9-asym", "X5-asym"), ("X9-mixed", "X5-mixed"), ("CR9-asym", "Criteo-asym"), ("CR9-mixed", "Criteo-mixed")]


def methods_table():
    src = (F2 / "table.tex").read_text()
    src = src.replace("\\begin{table}[t]", "\\begin{table*}[t]").replace("\\end{table}", "\\end{table*}")
    hdr = "% adapted (table -> table*) by writing/scripts/gen_r5_supp_tables.py from exp/results/full/v8_posthoc_F2/table.tex\n"
    (OUT / "f2_methods.tex").write_text(hdr + src)


def fmt(d):
    return f"{d['ratio']:.3f} {{\\scriptsize[{d['ci95'][0]:.3f}, {d['ci95'][1]:.3f}]}}"


def h2h_table():
    s = json.load(open(F2 / "summary.json"))
    rows = []
    for env, name in ENVS:
        h = s["envs"][env]["head_to_head"]
        for n in (250, 1000):
            fz = f"FDC-BF[ney-pilot,n={n}]"
            eq_r = h[f"{fz} / PJC-A-reset[pilot n={n},init+warm]"]["J1"]
            eq_m = h[f"{fz} / PJC-A-menu[pilot n={n},init+warm]"]["J1"]
            ch_r = h[f"{fz} / PJC-A-reset[no pilot]"]
            ch_m = h[f"{fz} / PJC-A-menu[no pilot]"]
            be = lambda d: f"{d['breakeven_J']:.2f}" if d.get("breakeven_J") is not None else "never"  # noqa: E731
            rows.append(f"{name} & {n:,} & {fmt(eq_r)} & {fmt(eq_m)} & {fmt(ch_r['J1'])} & {be(ch_r)} & {fmt(ch_m['J1'])} & {be(ch_m)} \\\\")
    body = "\n".join(rows)
    tex = r"""% generated by writing/scripts/gen_r5_supp_tables.py from exp/results/full/v8_posthoc_F2/summary.json
\begin{table*}[t]
\caption{\textbf{Block F2: frozen pilot-Neyman FDC-BF against the adaptive picks} (semi-synthetic, post hoc, descriptive; 250 streams per regime). Ratio = paired geometric mean of $N_{80}$, frozen pilot-Neyman FDC-BF / adaptive design, with 95\% bootstrap CI ($<1$: the frozen plan reads fewer rows). \emph{Equal information}: the adaptive design receives the same per-stream pilot (phase-0 pilot-Neyman plan plus pooled variance warm start) and both sides pay the same pilot. \emph{Charged pilot}: the frozen plan pays its pilot in full ($J = 1$) and the adaptive pick learns without a pilot; break-even $J$ = number of certification runs that must share one pilot before the frozen plan is faster. No method had a false stream.}
\label{tab:posthocF2h2h}
\small
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lrllllll@{}}
\toprule
& & \multicolumn{2}{c}{Equal information ($J = 1$)} & \multicolumn{4}{c}{Charged pilot vs no-pilot adaptive pick ($J = 1$)} \\
Regime & Pilot $n$ & vs reset & vs menu & vs reset & break-even $J$ & vs menu & break-even $J$ \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    (OUT / "f2_h2h.tex").write_text(tex)


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    methods_table()
    h2h_table()
    print("wrote", sorted(p.name for p in OUT.glob("*.tex")))
