"""Supplement S20 (revision r6d): localised union ledgers, development halves only (read-only on result rows).

Writes exp/results/pilots/fdc_pw/s20_summary.json with
  - ratios: paired geometric mean of N80_pen, v11 variant / TU-FDC-DP(b), per (cell, eps), on matched (seed, eps)
    pairs against exp/results/full/v10_posthoc_G/rows/G1-dev-*.jsonl; n = number of matched streams (50 = complete);
  - diag (only with --diag, needs the development halves): Hamming distance from the frozen-score reference policy to
    the true development optimum, and its true value gap, per problem.
and the LaTeX table writing/supplement/r6_tables/s20_ratios.tex (complete cells only).
Usage (iter_001): python writing/scripts/gen_r6d_s20.py [--diag]
"""
import json
import math
import sys
from collections import defaultdict
from pathlib import Path

IT = Path(__file__).resolve().parents[2]
RES = IT / "exp/results"
PW = RES / "pilots/fdc_pw"
VARIANTS = {"FDC-PW": ("rows_v1_twocentre", "TU-FDC-PW(b)"), "FDC-LS": ("rows", "TU-FDC-LS(a)")}
BASE = "TU-FDC-DP(b)"
CELLS = ["x5-16", "x5-32", "x5-64", "lenta-16", "lenta-32", "lenta-64"]


def load(p, meth):
    """Rows of one method from a .jsonl file or its .jsonl.gz copy (anonymous package)."""
    import gzip
    d = {}
    gz = p.with_name(p.name + ".gz")
    if p.exists():
        lines = p.read_text().splitlines()
    elif gz.exists():
        lines = gzip.open(gz, "rt").read().splitlines()
    else:
        return d
    for line in lines:
        r = json.loads(line)
        if r.get("method") == meth and not r.get("error"):
            d[(r["eps"], r["seed"])] = r
    return d


def ratios():
    out = {}
    for name, (sub, meth) in VARIANTS.items():
        for cell in CELLS:
            v = load(PW / sub / f"G1-dev-{cell}.jsonl", meth)
            b = load(RES / f"full/v10_posthoc_G/rows/G1-dev-{cell}.jsonl", BASE)
            by = defaultdict(list)
            for (e, s) in v:
                if (e, s) in b:
                    by[e].append(math.log(v[(e, s)]["N80_pen"] / b[(e, s)]["N80_pen"]))
            for e, lr in sorted(by.items()):
                n_false = sum(v[(e, s)]["n_false"] for (e2, s) in v if e2 == e)
                out[f"{name}|{cell}|{e}"] = {"variant": name, "cell": cell, "eps": e, "n": len(lr),
                                             "geomean": math.exp(sum(lr) / len(lr)), "n_false": n_false,
                                             "min_ratio": math.exp(min(lr))}
    return out


def diag():
    sys.path.insert(0, str(IT / "exp/code"))
    import numpy as np
    import run_v10_posthoc_G as G
    from dsswm.baselines.fdc_dp import dp_argmax
    from dsswm.envs.pw_reference import pw_ref_vals
    res = {}
    for cell in CELLS:
        cid = f"G1-dev-{cell}"
        G.init_env(cid)
        env = G._ENV["env"]
        data, S = cell.split("-")
        ref_vals, _ = pw_ref_vals(data, int(S))
        vals = np.asarray(env.w)[:, None] * G._ENV["mu"]
        ham, gap = [], []
        for q in range(env.problems.Q):
            B = int(env.problems.budgets[q])
            jstar, pstar = dp_argmax(vals, env.problems.cost, B)
            _, pref = dp_argmax(ref_vals, env.problems.cost, B)
            pref = np.asarray(pref)
            ham.append(int(np.sum(np.asarray(pstar) != pref)))
            gap.append(float(jstar - sum(vals[s, int(pref[s])] for s in range(len(pref)))))
        res[cell] = {"hamming": ham, "value_gap": gap}
    return res


def table(R):
    rows = []
    for cell in CELLS:
        for name in VARIANTS:
            c = [x for x in R.values() if x["variant"] == name and x["cell"] == cell and x["n"] == 50]
            part = [x for x in R.values() if x["variant"] == name and x["cell"] == cell and x["n"] < 50]
            log, S = cell.split("-")
            lab = f"{'X5' if log == 'x5' else 'Lenta'}, {S}"
            if c:
                lo, hi = min(x["geomean"] for x in c), max(x["geomean"] for x in c)
                rng = f"{lo:.3f}" if f"{lo:.3f}" == f"{hi:.3f}" else f"{lo:.3f}--{hi:.3f}"
                cov = f"{len(c)} of 6"
            else:
                rng, cov = "--", "0 of 6"
            pn = ", ".join(f"{x['n']}" for x in sorted(part, key=lambda x: x["eps"]))
            rows.append(f"{lab} & {name} & {cov} & {rng} & {pn if pn else '--'} \\\\")
    return "\n".join(rows)


TABLE_HEAD = r'''\begin{table}[H]
\caption{\textbf{Localised ledgers against FDC-DP} (development halves only; post hoc, descriptive). Paired geometric mean of $\Npen$, variant / TU-FDC-DP(b), on the same development streams (seeds 950--999) and tolerance grid as the block-G1 development cells. Ratio: range over the $\eps$ with all 50 streams (``complete''). Stopped: streams present in the $\eps$ at which the run was stopped, not reported as ratios. No false certificate in any row. Generated by \texttt{writing/scripts/gen\_r6d\_s20.py} from \texttt{exp/results/pilots/fdc\_pw/}.}
\label{tab:s20}
\footnotesize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}llllr@{}}
\toprule
Log, $S$ & Variant & Complete $\eps$ & Ratio & Stopped \\
\midrule
'''
TABLE_TAIL = r'''\bottomrule
\end{tabular}
\end{table}
'''


def main():
    R = ratios()
    out = {"ratios": R}
    f = PW / "s20_summary.json"
    if "--diag" in sys.argv:
        out["diag"] = diag()
    elif f.exists() and "diag" in json.loads(f.read_text()):
        out["diag"] = json.loads(f.read_text())["diag"]
    f.write_text(json.dumps(out, indent=1))
    t = IT / "writing/supplement/r6_tables/s20_ratios.tex"
    t.write_text("% generated by writing/scripts/gen_r6d_s20.py; do not edit by hand\n" + TABLE_HEAD + table(R) + "\n"
                 + TABLE_TAIL)
    print(f, t)


if __name__ == "__main__":
    main()
