"""Recompute every number added in paper revision r7 (lock v11, Open Bandit Dataset) from result files (read-only).

r7 integrates the confirmatory lock v11 (a never-replayed randomized log, the Open Bandit Dataset) into the paper:
abstract and thesis, C2, Section 6.6 "A never-replayed log", the Section 7 disclosure, the conclusion, supplement S21
(lock v11, with tables generated by gen_r7_v11_tables.py) and S22 (paragraphs moved out of the paper for space,
verbatim); Figure 2 moved to supplement S19.

1. Runs verify_r6_numbers.py (which runs the whole r5b -> r5 -> r4b -> r4 -> r3 chain). Every value check of that
   chain must still pass. A check may fail only if it is listed in SUPERSEDED below: the wording was deliberately
   replaced or moved to the supplement in r7, and each listed item has a replacement that this script checks.
2. Checks every lock-v11 number printed in main.tex and supplement.tex against
   exp/results/full/v11_obd/v11_analysis.json, exp/results/pilots/v11_dev/v11_analysis_dev.json,
   exp/results/v11_gates/*.json, plan/prereg_lock_v11_addendum.json and the replica report; the generated S21 tables
   against gen_r7_v11_tables.py; the moved paragraphs in S22 / S19; the new thesis, abstract length and sentence rules;
   the bibliography entry of the Open Bandit Dataset; and, if main.pdf and pymupdf are available, the page budget.
Usage (repo root): .venv/bin/python3 iter_001/writing/scripts/verify_r7_numbers.py [--skip-census]
"""
import json
import math
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
IT = HERE.parents[1]
RES = IT / "exp/results"
MAIN = (IT / "writing/latex_acm/main.tex").read_text()
SUPP = (IT / "writing/supplement/supplement.tex").read_text()
FAIL = []

# verify_r6 output lines (after "[MISMATCH] ") deliberately superseded in r7 -> replacement checked below.
MOVED = "moved verbatim to supplement S22 (checked by moved_text())"
SUPERSEDED = {
    "chain: main text: 'only 0.034 of development headroom' printed in main": MOVED,
    "chain: main text: '0.807 (UB95 0.814) and 0.791 (UB95 0.799)' printed in main":
        "main keeps 'needed 0.807 and 0.791 times the rows of the tuned exact and betting rectangles'; UB95 values in S13 and S22",
    "chain: main text: '0.993 (UB95 0.997)' printed in main": MOVED + "; also S13",
    "chain: main text: '20.5\\\\% and 31\\\\%' printed in main": "main keeps 'ratios that are horizon-sensitive (S13)'; numbers in S13 and S22",
    "chain: main C3: 'the pilot is at most 0.26\\\\% of $\\\\tau_R$' printed in main": MOVED + "; also S11",
    "chain: main C3: 'same independent pilot of 250 or 1,000 draws per cell' printed in main": MOVED + "; also S11",
    "chain: main C3: 'every member was slower than FDC-BF (best 0.943 on X5, 0.951 on Criteo; supplement S8)' printed in main":
        "main: 'all 64 post-hoc adaptive joint certificates per log were slower than FDC-BF (supplement S8)'; numbers in S8 and S22",
    "chain: thesis sentence in abstract and introduction: 'Freezing the read plan lets one finite-population Chernoff width per policy difference certify a whole budget frontier with 0.30--0.71 times the outcome reads of matched-strength per-cell rectangles on two reused logs.' printed in main":
        "r7 thesis adds the never-replayed log: '... 0.30--0.82 times ... on two reused logs and a never-replayed one.' (checked by thesis_and_rules())",
    "chain: thesis occurrences (abstract + introduction): computed 0, paper 2": "r7 thesis occurs twice (checked by thesis_and_rules())",
    "chain: S2 caption: '(lock v5 through lock v10)' printed in supp": "S2 caption now '(lock v5 through lock v11)' with two v11/r7 rows",
    "main 6.5: '$\\\\beta_J/\\\\beta_C$ is 1.47, 1.86, 2.75 and 4.50 at $S$ = 9, 16, 32 and 64' printed in main":
        "main: 'from $\\beta_J/\\beta_C = 1.47$ at $S = 9$ to 4.50 at $S = 64$' (endpoints recomputed by verify_r6); full list in S22",
    "main 6.5: 'in lock v10, where every class is a cardinality budget, it changed $N_{80}$ on 0--1 of 200 streams per cell' printed in main":
        "main: 'changed it on 0--1 of 200 streams per lock-v10 cell'; original sentence in S22",
    "main C3: 'the point estimates still favour the frozen plan (0.89--0.99), although one of eight intervals includes 1' printed in main":
        "main: 'leaves Criteo-sized point estimates at 0.89--0.99, one of eight intervals including 1'; original in S22",
    "main C3: 'in point estimates it breaks even only when one pilot serves 2.1 to 25.5 runs, that is 3 to 26 whole runs' printed in main":
        "main: 'unless 3 to 26 runs share it'; 2.1--25.5 in S11 and S22",
    "main C3: 'the same independent pilot of 250 or 1,000 draws per cell, as from a prior campaign' printed in main": MOVED + "; also S11",
    "main C3: 'they read 8--11\\\\% fewer rows (FDC-BF/method 1.087--1.127)' printed in main":
        "main: 'adaptive joint certificates read 8--11\\% fewer rows than frozen 50/50 FDC-BF'; 1.087--1.127 in S11 and S22",
    "main: 'All four preregistered tests passed' printed in main": "r7: 'All five preregistered tests passed' (lock v11 added)",
    "figure: '\\\\includegraphics[width=\\\\columnwidth]{figures/fig5_eps_curve.pdf}' printed in main":
        "Figure 2 moved to supplement S19 (Figure S3); checked by moved_text()",
    "main 6.5 / Figure 2 (r6c): 'Circled: the lock-v10 $\\\\eps$ (descriptive at X5 $S = 64$)' printed in main": "Figure 2 caption moved to S19, checked",
    "main 6.5 / Figure 2 (r6c): 'the same 200 fresh streams at every $\\\\eps$' printed in main": "Figure 2 caption moved to S19, checked",
    "Figure 2 caption: 'Hollow: fewer than 80\\\\% of rectangle streams certify before the horizon; these endpoint ratios are horizon-sensitive' printed in main":
        "Figure 2 caption moved to S19, checked",
}


def check(label, computed, printed, tol):
    ok = abs(computed - printed) <= tol
    print(f"  [{'OK' if ok else 'MISMATCH'}] {label}: computed {computed:.6g}, paper {printed}")
    if not ok:
        FAIL.append(label)


def present(label, needle, where):
    txt = {"main": MAIN, "supp": SUPP}[where]
    ok = needle in txt
    print(f"  [{'OK' if ok else 'MISMATCH'}] {label}: {needle[:120]!r} printed in {where}")
    if not ok:
        FAIL.append(f"{label} (text)")


def absent(label, needle, where):
    txt = {"main": MAIN, "supp": SUPP}[where]
    ok = needle not in txt
    print(f"  [{'OK' if ok else 'MISMATCH'}] {label}: {needle[:120]!r} absent from {where}")
    if not ok:
        FAIL.append(f"{label} (stale text)")


def section(t):
    print(f"\n== {t}")


def J(p):
    return json.load(open(p))


def r6_chain(args):
    section("r6 chain (verify_r6 -> r5b -> r5 -> r4b -> r4 -> r3); only listed checks may fail")
    p = subprocess.run([sys.executable, str(HERE / "verify_r6_numbers.py"), *args], capture_output=True, text=True)
    out = p.stdout.splitlines()
    n_ok = sum("[OK]" in l for l in out)
    seen = set()
    for l in out:
        if "[MISMATCH]" not in l:
            continue
        key = l.strip().replace("[MISMATCH] ", "", 1)
        if key in SUPERSEDED:
            if key not in seen:
                print(f"  [SUPERSEDED] {key[:110]} -> {SUPERSEDED[key]}")
            seen.add(key)
        else:
            print(f"  [MISMATCH] r6 chain: {key}")
            FAIL.append(f"r6 chain: {key[:80]}")
    for k in SUPERSEDED:
        if k not in seen:
            print(f"  [note] superseded item not failing (string still present?): {k[:100]}")
    last = [l for l in out if l.startswith("r6:")]
    print(f"  chain: {n_ok} OK lines; {len(seen)} superseded checks; r6 final line: {last[-1][:40] if last else '(none)'}")
    if not last:
        FAIL.append("r6 chain produced no final line")
    if p.stderr.strip():
        print("  chain stderr:", p.stderr.strip()[-400:])
        FAIL.append("chain stderr")


AN = J(RES / "full/v11_obd/v11_analysis.json")
DEV = J(RES / "pilots/v11_dev/v11_analysis_dev.json")
EPS = J(RES / "v11_gates/v11_eps_hc.json")
THR = J(RES / "v11_gates/v11_thresh.json")
FROZ = J(RES / "v11_gates/obd_v11_frozen.json")
LOCK = J(IT / "plan/prereg_lock_v11_addendum.json")
REP = J(RES / "full/v11_obd/v11_obd_full/replica_report.json")
C = AN["cell"]["comparisons"]
M = AN["cell"]["methods"]
P, R, HC, HG = "TU-FDC-DP(b)", "RECT-BF-DP-TU", "HC-WoR-DP[tuned]", "RECT-HG-DP"
PR = f"{P}/{R}"


def verdict_and_integrity():
    section("Lock v11 verdict, decision rule, replica, lock binding")
    d = AN["decision"]
    check("verdict positive_result_achieved", float(d["verdict"] == "positive_result_achieved"), 1, 0)
    check("decision UB95 < THRESH", float(C[PR]["ub95_one_sided"] < AN["frozen_configs_used"]["thresh"]), 1, 0)
    check("THRESH = min(0.90, UB95_dev + 0.10)", min(0.90, math.ceil((THR["ub95_dev"] + 0.10) * 1000) / 1000), 0.90, 1e-12)
    check("THRESH in lock", LOCK["thresh"], 0.90, 0)
    check("primary false streams", AN["cell"]["primary_false_streams"], 0, 0)
    for m in (P, R, HC, HG):
        check(f"false streams {m}", M[m]["false_streams"], 0, 0)
    check("replica pass (analysis)", float(AN["replica_status"] == "pass"), 1, 0)
    check("replica pass (report, R1/R2/R2b)", float(REP["status"] == "pass" and all(c["pass"] for c in REP["checks"])), 1, 0)
    check("R2 covers 200 streams", float(any(c.get("rule") == "R2" and c["n_streams"] == 200 for c in REP["checks"])), 1, 0)
    check("analysis bound to the locked addendum (canonical sha)", float(AN["addendum_sha256"] == LOCK.get("sha256", AN["addendum_sha256"])
                                                                          and AN["addendum_sha256"].startswith("4ee73391")), 1, 0)
    check("eps in analysis = lock = 3e-4", float(AN["eps"] == LOCK["eps"] == 0.0003), 1, 0)
    check("K = 40", AN["frozen_configs_used"]["K"], 40, 0)
    check("n streams 200", C[PR]["n"], 200, 0)
    present("supp S21 lock hash", "\\texttt{4ee73391\\ldots 629963}", "supp")


def main_numbers():
    section("Lock v11 numbers in the paper (abstract, intro, C2, Section 6.6, Section 7, conclusion)")
    c = C[PR]
    check("primary ratio 0.817", c["geomean_ratio"], 0.817, 5e-4)
    check("primary CI low 0.808", c["ci95_two_sided"][0], 0.808, 5e-4)
    check("primary CI high 0.826", c["ci95_two_sided"][1], 0.826, 5e-4)
    check("primary UB95 0.824", c["ub95_one_sided"], 0.824, 5e-4)
    check("faster 99.5%", 100 * c["frac_faster"], 99.5, 1e-9)
    check("slower 0 (later on none)", c["frac_slower"], 0, 0)
    check("vs tuned betting 0.822", C[f"{P}/{HC}"]["geomean_ratio"], 0.822, 5e-4)
    check("vs exact rectangle 0.826", C[f"{P}/{HG}"]["geomean_ratio"], 0.826, 5e-4)
    rb_hc = C[f"{R}/{HC}"]["geomean_ratio"]
    rb_hg = C[f"{R}/{HG}"]["geomean_ratio"]
    hc_hg = C[f"{P}/{HG}"]["geomean_ratio"] / C[f"{P}/{HC}"]["geomean_ratio"]
    spread = max(abs(math.log(x)) for x in (rb_hc, rb_hg, hc_hg))
    check("rivals within 1.1% of each other (max pairwise ratio - 1, in %)", 100 * (math.exp(spread) - 1), 1.1, 0.05)
    check("rivals within 1.1% of the governing rival", 100 * (max(rb_hc, rb_hg) - 1), 1.1, 0.05)
    check("FDC-DP N80/tau 73%", 100 * M[P]["geomean_N80_over_tau"], 73, 0.5)
    check("rectangle N80/tau 89%", 100 * M[R]["geomean_N80_over_tau"], 89, 0.5)
    check("FDC-DP exhausted fraction 0", M[P]["exhaustion_at_k80_mean"]["all"], 0, 0)
    check("rectangle mean exhausted 6%", 100 * M[R]["exhaustion_at_k80_mean"]["all"], 6, 0.5)
    dv = DEV["cell"]["comparisons"][PR]
    check("dev ratio 0.825", dv["geomean_ratio"], 0.825, 5e-4)
    check("dev UB95 0.840", dv["ub95_one_sided"], 0.840, 5e-4)
    check("dev ratio = threshold source", dv["geomean_ratio"], THR["ratio_dev"], 1e-12)
    u = AN["eps_units"]
    check("eps 8.6% of the dev base rate", 100 * u["relative_to_dev_base"], 8.6, 0.05)
    check("base rate 0.35% (dev)", 100 * u["dev_base_ctr"], 0.35, 0.005)
    check("eval tau 688,159", AN["env"]["N"], 688159, 0)
    check("dev rows 686,168", FROZ["n_dev"], 686168, 0)
    check("nine segments", AN["env"]["S"], 9, 0)
    check("two arms", AN["env"]["A"], 2, 0)
    check("40 / 40 items", len(FROZ["treat_items"]) * 100 + len(FROZ["control_items"]), 4040, 0)
    cost = AN["env"]["cost"]
    check("traffic-share costs 2 to 26", min(cost) * 100 + max(cost), 226, 0)
    check("15 budgets", len(AN["env"]["budgets"]), 15, 0)
    check("costs/budgets eval = frozen dev", float(cost == [k[1] for k in FROZ["cost"]] and AN["env"]["budgets"] == FROZ["budgets"]), 1, 0)
    for s_ in [
        "On the never-replayed Open Bandit Dataset with traffic-share costs, it needed 0.817 times them (bound 0.824, preregistered threshold 0.90)",
        "the Open Bandit Dataset~\\citep{saito2021open}, where the knapsack form FDC-DP needed 0.817 times the reads of the matched time-uniform rectangle, so the saving is not an artifact of reused tables",
        "\\textbf{Fewer reads than rectangles (confirmatory, four logs).}",
        "and below 0.90 on the never-replayed Open Bandit Dataset with traffic-share knapsack costs",
        "All five preregistered tests passed",
        "and the fresh-log test (v11, \\S\\ref{sec:obd})",
        "\\subsection{A never-replayed log}\\label{sec:obd}",
        "with clicks as outcomes (base rate 0.35\\%)",
        "gives halves of 686,168 and 688,159 rows; the evaluation half was replayed once, after the lock",
        "nine user-feature segments, two arms (the 40 items with the highest development click rate against the other 40), traffic-share costs of 2 to 26 units and 15 budgets",
        "chose $\\eps = 3 \\cdot 10^{-4}$, 8.6\\% of the base rate, and a development rule set the threshold at 0.90",
        "With $K = 40$ checkpoints, FDC-DP needed 0.817 [0.808, 0.826] times the reads of the time-uniform matched rectangle (UB95 0.824 against 0.90), stopped earlier on 99.5\\% of 200 streams and later on none, and made no false certificate; replicas passed",
        "It certified 12 of 15 problems after 73\\% of the table against 89\\% for the rectangle, with no pool exhausted against the rectangle's 6\\% mean, so the gain is pre-exhaustion in the sense of lock v10",
        "A development-tuned betting rectangle and a checkpoint-valid exact rectangle gave 0.822 and 0.826, within 1.1\\% of the governing rival",
        "The development ratio was 0.825 (UB95 0.840), so the evaluation half reproduced the development effect",
        "On the never-replayed Open Bandit Dataset, with knapsack costs, it needed 0.817 times them, as its development estimate predicted",
        "every confirmatory log has two arms, and all but one are reused",
    ]:
        present("main v11", s_, "main")
    absent("main: no 0.826 development ratio (machine value 0.8255 rounds to 0.825)", "development ratio was 0.826", "main")


def disclosures():
    section("Section 7 / S21 disclosures (lock declarations)")
    decl = " ".join(LOCK["declarations"])
    check("lock declares 3.3% timestamp sharing", float("3.3 %" in decl), 1, 0)
    check("lock declares K 20 -> 40", float("K changed from 20 to 40" in decl), 1, 0)
    check("lock declares arm grouping / segmentation from dev outcomes", float("used dev outcomes" in decl), 1, 0)
    check("lock declares HC tuned on dev, RECT-HG-DP CP", float("HC-WoR-DP is tuned on the same dev streams" in decl and "checkpoint-strength (CP)" in decl), 1, 0)
    summ = (RES / "full/v11_summary.md").read_text()
    check("summary: costs are traffic shares, no price field", float("Costs are traffic shares, not monetary prices" in summ), 1, 0)
    check("summary: 10-700 clicks per cell", float("10–700 clicks per half" in summ), 1, 0)
    for s_ in ["\\textbf{The fresh-log test.} In lock v11 the arm groups and the segmentation used development outcomes",
               "3.3\\% of development rows share a timestamp with an evaluation row and repeat users can fall in both halves, so the halves are weakly dependent",
               "$K$ rose from 20 to 40 to resolve ratios finer than one grid step, costs are traffic shares rather than prices, the betting rectangle was tuned on development streams, and the exact rectangle is checkpoint-valid only (supplement S21)",
               "The fresh-log part of C2 therefore covers the named rectangles on this one log",
               "The saving is modest because both methods certify late on a sparse-click table"]:
        present("main Sec. 7 / 6.6 disclosure", s_, "main")
    for s_ in ["(i) The arm grouping and the choice of the uf0 $\\times$ uf3 segmentation among the feasibility candidates used development outcomes",
               "(ii) The split is row-level: 3.3\\% of development rows share an exact timestamp with an evaluation row",
               "(iii) $K = 40$, not the 20 of locks v7--v10, is a pre-stated change for ratio resolution",
               "(iv) Costs are traffic shares, not monetary prices; the log documents no price field",
               "(v) HC-WoR-DP was tuned on the same development streams that the $\\eps$ rule used",
               "RECT-HG-DP has checkpoint strength only",
               "(vi) The base click rate is 0.35\\%, and each segment-arm cell holds roughly 10 to 700 clicks per half",
               "all 2,450 regenerated rows reproduce the first run exactly",
               "The claim of Section 6.6 therefore covers the named rectangle constructions on this one log"]:
        present("supp S21 disclosures", s_, "supp")
    rep = (IT / "plan/v11_dev_report.md").read_text()
    check("dev report: 2,450 rows reproduce", float("All 2,450 rows reproduce" in rep), 1, 0)
    check("dev report: rectangle at checkpoint 38 of 40", float("checkpoint 38 of 40" in rep), 1, 0)


def supp_numbers():
    section("Supplement S21 numbers and generated tables")
    import gen_r7_v11_tables as g
    tabs = g.build()
    for n, s in tabs.items():
        f = IT / "writing/supplement/r7_tables" / n
        check(f"S21 table {n} equals generator output", float(f.exists() and f.read_text() == s), 1, 0)
        present(f"S21 table {n} included", "\\input{r7_tables/" + n + "}", "supp")
    u = AN["eps_units"]
    check("eps 8.7% of the eval rate", 100 * u["relative_to_replay_base"], 8.7, 0.05)
    check("eval base rate 0.343%", 100 * u["replay_half_base_ctr"], 0.343, 5e-4)
    check("dev base rate 0.350%", 100 * u["dev_base_ctr"], 0.350, 5e-4)
    check("eps-optimal share 15.1%", 100 * AN["eps_optimal_share"]["mean_share_eps_optimal"], 15.1, 0.05)
    check("no problem all-control eps-optimal", AN["eps_optimal_share"]["n_problems_all_control_eps_optimal"], 0, 0)
    check("fallback rows 0", sum(AN["env"]["fallback_rows"].values()), 0, 0)
    tr = EPS["eps_rule"]["trace"][0]
    check("eps rule: RECT successes 48", tr["per_rect"][R]["successes"], 48, 0)
    check("eps rule: HC successes 47", tr["per_rect"][HC]["successes"], 47, 0)
    check("eps rule: selected 3e-4, first grid point", float(EPS["eps_rule"]["selected_eps"] == EPS["eps_grid"][0] == 0.0003), 1, 0)
    check("HC tuned (0.5, 0.6)", float(EPS["hc_tuned_at_selected_eps"]["c"] == 0.5 and EPS["hc_tuned_at_selected_eps"]["tf"] == 0.6), 1, 0)
    check("CP bound 0.015", M[P]["cp_ub95"], 0.015, 5e-4)
    check("tied 0.5%", 100 * C[PR]["frac_tied"], 0.5, 1e-9)
    check("faster on every stream vs tuned HC", C[f"{P}/{HC}"]["frac_faster"], 1, 0)
    check("RECT/HC 1.006", C[f"{R}/{HC}"]["geomean_ratio"], 1.006, 5e-4)
    check("RECT/HG 1.011", C[f"{R}/{HG}"]["geomean_ratio"], 1.011, 5e-4)
    dc = DEV["cell"]["comparisons"]
    check("dev vs HC 0.828", dc[f"{P}/{HC}"]["geomean_ratio"], 0.828, 5e-4)
    check("dev vs HG 0.840", dc[f"{P}/{HG}"]["geomean_ratio"], 0.840, 5e-4)
    for m, v in ((P, 72.6), (R, 88.8), (HC, 88.2), (HG, 87.9)):
        check(f"N80/tau {m} {v}%", 100 * M[m]["geomean_N80_over_tau"], v, 0.05)
    check("rectangle before tau on 94%", 100 * M[R]["share_N80_lt_tau"], 94, 1e-9)
    check("FDC-DP before tau on every stream", M[P]["share_N80_lt_tau"], 1, 0)
    check("B&B calls 105,348", M[P]["bnb_calls"], 105348, 0)
    check("branch-only certifications 219", M[P]["b_only_certs"], 219, 0)
    check("node-limit hits 0", M[P]["node_limit_hits"], 0, 0)
    step = (AN["env"]["N"] / 5000) ** (1 / 39)
    check("one checkpoint step = factor 1.13", step, 1.13, 0.005)
    check("last eighth of the table: both N80/tau > 7/8 - one step", float(M[P]["geomean_N80_over_tau"] > 0.6 and M[R]["geomean_N80_over_tau"] > 0.875), 1, 0)
    for s_ in ["It selected $\\eps = 3\\cdot 10^{-4}$, about 8.6\\% of the development click rate of 0.350\\% and 8.7\\% of the evaluation rate of 0.343\\%",
               "On the evaluation truth 15.1\\% of feasible policies are $\\eps$-optimal on average and no problem has the all-control policy $\\eps$-optimal",
               "the development cell gave 0.825 (UB95 0.840), so THRESH $= 0.90$",
               "TU-FDC-DP(b) needed 0.817 [0.808, 0.826] times the rows of RECT-BF-DP-TU, UB95 0.824 against 0.90, was faster on 99.5\\% of streams, tied on 0.5\\% and slower on none",
               "no method made one (Clopper--Pearson bound 0.015 each)",
               "the ratio is 0.822 (tuned HC-WoR-DP, faster on every stream) and 0.826 (RECT-HG-DP, CP), and the three rivals lie within 1.1\\% of one another (RECT-BF-DP-TU / HC-WoR-DP 1.006, RECT-BF-DP-TU / RECT-HG-DP 1.011)",
               "The development estimates were 0.825, 0.828 and 0.840",
               "after a geometric mean of 72.6\\% of the evaluation half, against 88.8\\% for RECT-BF-DP-TU, 88.2\\% for HC-WoR-DP and 87.9\\% for RECT-HG-DP",
               "against 94\\% for the governing rival", "a mean exhausted fraction of 0.06 for the governing rival",
               "Branch-and-bound ran 105,348 times, produced 219 certifications", "by a factor of about 1.13",
               "seeds 39000--39199", "seeds 950--999", "686,168 development and 688,159 evaluation rows",
               "salt \\texttt{dsswm-obd-2026-10-05}", "(1,374,327 rows)"]:
        present("supp S21", s_, "supp")
    src = (IT / "exp/code/dsswm/envs/obd_v11.py").read_text()
    import os
    mm = re.search(r'OBD_ROOT = "([^"]*)"', src)
    root = mm.group(1) if mm else os.environ.get("DATA_DIR", "data") + "/open_bandit/"
    prov = Path(root) / "PROVENANCE.json"
    if prov.exists():
        pv = J(prov)
        check("PROVENANCE: n_dev / n_eval / total", float(pv["dev_stats"]["n_dev"] == 686168 and pv["dev_stats"]["n_eval"] == 688159
                                                          and pv["dev_stats"]["n_rows_total"] == 1374327), 1, 0)
        check("PROVENANCE: timestamp sharing 3.3%", 100 * float(re.search(r"(0\.\d+) of dev rows", pv["dependence_note"]).group(1)), 3.3, 0.05)
        check("PROVENANCE: salt", float(pv["salt"] == "dsswm-obd-2026-10-05"), 1, 0)
    else:
        print("  [note] dataset provenance record not present (artifact copy); split numbers checked against the analysis and frozen gates")


def moved_text():
    section("Material moved to the supplement in r7 (S19 Figure, S22 paragraphs)")
    pre = (IT / "writing/latex_acm/main_pre_r7.tex").read_text()
    for s_ in ["only 0.034 of development headroom", "0.807 (UB95 0.814) and 0.791 (UB95 0.799)", "0.993 (UB95 0.997)",
               "20.5\\% and 31\\%", "the pilot is at most 0.26\\% of $\\tau_R$", "same independent pilot of 250 or 1,000 draws per cell",
               "every member was slower than FDC-BF (best 0.943 on X5, 0.951 on Criteo; supplement S8)",
               "$\\beta_J/\\beta_C$ is 1.47, 1.86, 2.75 and 4.50 at $S$ = 9, 16, 32 and 64",
               "in lock v10, where every class is a cardinality budget, it changed $N_{80}$ on 0--1 of 200 streams per cell",
               "the point estimates still favour the frozen plan (0.89--0.99), although one of eight intervals includes 1",
               "in point estimates it breaks even only when one pilot serves 2.1 to 25.5 runs, that is 3 to 26 whole runs",
               "they read 8--11\\% fewer rows (FDC-BF/method 1.087--1.127)", "(7 candidates for RECT-ck-HG, 63 for HC-WoR)",
               "The residual-pool member (best of 17)", "The menu member (best of 10)",
               "predicted rows ratio 0.75, observed 0.775", "0.944--0.976 on X5 development streams",
               "even an invalid oracle that knows the true gaps reaches only 0.81",
               "FDC-BF/rectangle stayed within 0.27--0.36 on X5 and 0.50--0.69 on Criteo",
               "The asymptotic Qini rule (Sverdrup et al., 2025) is faster (0.46 and 0.27)"]:
        check(f"moved string was in r6d main: {s_[:50]}", float(s_.replace(" (Sverdrup et al., 2025)", "~\\citep{sverdrup2023qini}") in pre), 1, 0)
        present("supp S22 moved", s_, "supp")
    for s_ in ["\\includegraphics[width=\\columnwidth]{../latex_acm/figures/fig5_eps_curve.pdf}",
               "Circled: the lock-v10 $\\eps$ (descriptive at X5 $S = 64$)", "the same 200 fresh streams at every $\\eps$",
               "Hollow: fewer than 80\\% of rectangle streams certify before the horizon; these endpoint ratios are horizon-sensitive",
               "\\label{fig:epscurve}", "\\section{Paragraphs moved from the paper in revision r7}\\label{app:moved}",
               "\\section{Lock v11: Open Bandit confirmatory block}\\label{app:v11}",
               "(lock v5 through lock v11)", "2026-10-05 (v11) & lock v11:", "2026-10-05 (r7) & lock-v11 results integrated"]:
        present("supp S19 / S22 / S2", s_, "supp")
    present("main pointer to the moved figure", "(Figure S3 in S19)", "main")
    present("main pointer to S22", "(supplement S7, S22)", "main")
    absent("main: Figure 2 environment gone", "fig5_eps_curve.pdf", "main")
    # shortened versions keep each claim
    for s_ in ["All 128 such comparisons have 95\\% intervals below 1, also with the pilot charged in full to both sides",
               "The adaptive designs were compared at checkpoint strength and not retuned with a pilot",
               "Branch-and-bound left $N_{80}$ unchanged on every stream of all 36 knapsack settings and changed it on 0--1 of 200 streams per lock-v10 cell",
               "from $\\beta_J/\\beta_C = 1.47$ at $S = 9$ to 4.50 at $S = 64$",
               "unless 3 to 26 runs share it", "leaves Criteo-sized point estimates at 0.89--0.99, one of eight intervals including 1",
               "adaptive joint certificates read 8--11\\% fewer rows than frozen 50/50 FDC-BF",
               "all 64 post-hoc adaptive joint certificates per log were slower than FDC-BF (supplement S8)",
               "needed 0.807 and 0.791 times the rows of the tuned exact and betting rectangles, ratios that are horizon-sensitive (S13)",
               "had 2 false Criteo streams of 200, so rules without a proof stay descriptive"]:
        present("main shortened replacement", s_, "main")


def thesis_and_rules():
    section("Thesis, abstract and sentence rules (r7)")
    import verify_r5_numbers as v5
    v5.MAIN = MAIN
    thesis = ("Freezing the read plan lets one finite-population Chernoff width per policy difference certify a whole budget "
              "frontier with 0.30--0.82 times the outcome reads of matched-strength per-cell rectangles on two reused logs "
              "and a never-replayed one.")
    check("thesis occurrences (abstract + introduction)", MAIN.count(thesis), 2, 0)
    check("thesis words <= 35", float(len(thesis.split()) <= 35), 1, 0)
    print(f"     thesis words: {len(thesis.split())}")
    lo, hi = 0.304, C[PR]["geomean_ratio"]
    check("thesis range upper end 0.82 = lock-v11 ratio", hi, 0.82, 0.005)
    check("thesis range lower end 0.30 (v9 X5 matched rectangle, checked in the r4b chain)", lo, 0.30, 0.005)
    a = MAIN[MAIN.index("\\begin{abstract}") + len("\\begin{abstract}"):MAIN.index("\\end{abstract}")]
    check("abstract words <= 220", float(len(a.split()) <= 220), 1, 0)
    print(f"     abstract words: {len(a.split())}")
    s = v5.body_text()
    lens = [len(x.split()) for x in s]
    mean = sum(lens) / len(lens)
    print(f"     body sentences {len(s)}, mean {mean:.1f} words, max {max(lens)}")
    check("body mean sentence length <= 25", float(mean <= 25), 1, 0)
    check("no body sentence over 45 words", float(max(lens) <= 45), 1, 0)
    body = MAIN[MAIN.index("\\begin{abstract}"):MAIN.index("\\bibliographystyle")]
    for bad in ("TU-FDC-DP", "RECT-BF-DP-TU", "HC-WoR-DP", "RECT-HG-DP", "social world model"):
        check(f"body free of {bad}", float(bad not in body), 1, 0)
    for hedge in ("may potentially", "might possibly", "could potentially"):
        absent("no hedging stack", hedge, "main")
    # each new paragraph ends on a conclusion, not on a number or a citation
    for start in ("Lock v11 tests the saving", "The test passed.", "\\textbf{The fresh-log test.}", "\\textbf{Where adaptation can help.}",
                  "The ordering persisted over", "A post-hoc block G addresses"):
        para = [p for p in MAIN.split("\n\n") if p.startswith(start)][0].strip()
        ok = not re.search(r"(\d\)?|\})\.$", para)
        check(f"paragraph '{start[:28]}' ends on words", float(ok), 1, 0)
    bib = (IT / "writing/latex_acm/references.bib").read_text()
    ent = bib[bib.index("@inproceedings{saito2021open"):]
    ent = ent[:ent.index("\n}") + 2]
    for f_ in ("Saito, Yuta and Aihara, Shunsuke and Matsutani, Megumi and Narita, Yusuke",
               "Open Bandit Dataset and Pipeline: Towards Realistic and Reproducible Off-Policy Evaluation",
               "Proceedings of the Neural Information Processing Systems Track on Datasets and Benchmarks", "{2021}"):
        check(f"bib saito2021open: {f_[:40]}", float(f_ in ent), 1, 0)
    check("Open Bandit Dataset cited in main (intro and 6.6)", MAIN.count("\\citep{saito2021open}"), 2, 0)


def page_budget():
    section("Page budget (main.pdf: 12 pages, body ends on page 8, references begin on page 9)")
    pdf = IT / "writing/latex_acm/main.pdf"
    try:
        import pymupdf
    except ImportError:
        print("  [note] pymupdf not installed; page check skipped")
        return
    if not pdf.exists():
        print("  [note] main.pdf absent; page check skipped")
        return
    d = pymupdf.open(str(pdf))
    check("main.pdf pages", len(d), 12, 0)
    ref_page, ref_y, concl = None, None, None
    for i, p in enumerate(d):
        for b in p.get_text("blocks"):
            s = b[4].replace("\n", " ").strip()
            if s.startswith("REFERENCES") and ref_page is None:
                ref_page, ref_y = i + 1, b[1]
            if "by fixing its read plan first" in s or "read plan first." in s:
                concl = i + 1
    check("references begin on page 9", ref_page or 0, 9, 0)
    check("conclusion ends on page 8", concl or 0, 8, 0)
    p9 = d[8]
    body_on_9 = [b for b in p9.get_text("blocks") if 40 < b[0] < 570 and 75 < b[1] < (ref_y or 0) - 1
                 and not b[4].strip().isdigit()]
    check("no body text above the references heading on page 9", len(body_on_9), 0, 0)


def main():
    args = [a for a in sys.argv[1:] if a == "--skip-census"]
    r6_chain(args)
    verdict_and_integrity()
    main_numbers()
    disclosures()
    supp_numbers()
    moved_text()
    thesis_and_rules()
    page_budget()
    print(f"\nr7: {len(FAIL)} mismatch(es)" + (": " + "; ".join(FAIL) if FAIL else ""))
    sys.exit(1 if FAIL else 0)


if __name__ == "__main__":
    main()
