"""B4-bal (round 5): frozen balanced read schedule + per-cell rectangle ("radius-sum") certificate.

Same frozen, data-free design family as FDC (methodology s2.1 / s4.2): in every segment the control arm (column 0)
receives share ``share`` and the remaining A - 1 arms share 1 - share equally; the schedule is pre-generated by
``envs.pool_replay.make_schedule`` from the permutation seed and labels only (``alloc_kind = 'fixed'``); an exhausted
arm is re-selected with the pre-drawn uniform (``StreamEngine._resel``). The certificate is the r4
``frontier_common.rect_certificate`` (per-cell WSR20 time-uniform WoR CS, delta / (S A) per cell, radius sum over the
differing segments), which is rigorous under any sampling rule (the draws of a cell are a uniformly random
permutation of its pool), hence a fortiori under a frozen schedule.

Role: rigorous rival in R. With share = 0.5 it has EXACTLY the FDC design, so FDC / B4-bal isolates the
certificate-shape contribution (claim C4). The share is a tuning parameter (pre-declared grid
{0.40, 0.45, 0.50} on development seeds 900-949, methodology s4.4); every grid point stays rigorous.
"""
from __future__ import annotations

import numpy as np

from .frontier_common import Method, rect_certificate

__all__ = ["B4Bal", "B4BAL_SHARE_GRID", "balanced_alloc"]

B4BAL_SHARE_GRID = (0.40, 0.45, 0.50)


def balanced_alloc(S, A, share=0.5):
    """(S, A) allocation matrix: control share ``share`` in column 0, the rest split equally over arms 1..A-1."""
    if not 0.0 < share < 1.0:
        raise ValueError("share must lie in (0, 1) (a zero share starves a cell: U = +inf until exhaustion)")
    if A < 2:
        raise ValueError("need A >= 2")
    row = np.full(A, (1.0 - share) / (A - 1))
    row[0] = share
    return np.tile(row, (S, 1))


class B4Bal(Method):
    alloc_kind = "fixed"
    validity = "rigorous"

    def __init__(self, share=0.5, name="B4-bal"):
        self.share = float(share)
        self.name = name
        self.alloc_p = None

    def setup(self, ctx):
        self.alloc_p = balanced_alloc(ctx.S, ctx.A, self.share)

    def certify(self, ctx, st):
        return rect_certificate(ctx, st)

    def describe(self):
        d = super().describe()
        d.update({"share_control": self.share, "certificate": "rect (WSR20 WoR, delta/(S*A) per cell)",
                  "design": "frozen fixed shares (data-free)"})
        return d
