"""FDC (round 5, cand_fdc): frozen 50/50 read schedule + direction-level Bernstein certificate.

Unique specification: methodology s2 and plan/theory/fdc_theorem.md s1 (Theorem FDC-1). FDC reuses the r4 code paths
unchanged (r4 frozen at commit 6297e7f2); this module only adds the ledger and the design.

  * Design      : every segment control / treatment 0.5 / 0.5 (data-free; ``alloc_kind = 'fixed'``). The schedule is
                  pre-generated by ``envs.pool_replay.make_schedule`` from the permutation seed and labels only; an
                  exhausted arm is re-selected with the pre-drawn uniform (``StreamEngine._resel``), i.e. for A = 2
                  all later arrivals of that segment go to the other arm. Identical to B4-bal(share = 0.5).
  * Certificate : ``certify.quadknap.qfc_certificate_enum`` (Lemma L1 pair width sqrt(2 beta V_bar) + b beta / 3,
                  all feasible challengers, pi_hat = J_hat-argmax with lowest index on ties, exhausted cells exact,
                  n = 0 -> +inf) with variance UCB ``certify.quadknap.make_stats`` (Lemma L2 Bernstein inversion at
                  exponent x_v). Inherited verbatim from ``frontier_common.QFCMethod.certify``.
  * Ledger      : computed in ``setup`` from the ctx only, no override path:
                    beta = ln(sum_q |Pi_{B_q}| * K / delta_main),   x_v = ln(2 * S * A * K / delta_var),
                    (delta_main, delta_var) = (0.045, 0.005), sum = delta = 0.05.
                  CR9 dev: sum_q |Pi_{B_q}| = 3386, K = 20, S*A = 18 -> beta = 14.2242, x_v = 11.8776.

``FDCMethod()`` takes NO constructor arguments (no beta / x_v / share / delta / K override): it is the only object
whose results may enter a rigorous (headline) table.

``FDCAblation`` spans the 2 x 2 x 2 C4 factorial (methodology s6.3) and the T1 reconciliation:
    design in {'pool', 'half'}    pool proportions (r4 QFC) vs frozen 50/50 (FDC)
    union  in {'qstar', 'feas'}   Q * |Pi_all| (r4 Q*-union, ``l1_qstar``) vs sum_q |Pi_{B_q}| (FDC)
    ledger in {'r4', 'r5'}        (delta_main, delta_var, C_var) = (0.04, 0.01, 48) vs (0.045, 0.005, S*A)
All 8 cells are ledger-legal and get ``validity = 'rigorous'`` (the r4 ledger additionally requires 48 >= S*A, else
the variance union is undercounted and the cell is downgraded). Overrides that are not ledger-legal -- a constant
beta / x_v, a control share != 0.5 (exploratory record only, methodology s2.1), or K_override < number of
checkpoints -- set ``validity = 'none'`` and append '-explore' to the name, so that such a result can never be
counted as rigorous. ``FDCAblation('half', 'feas', 'r5')`` is numerically identical to ``FDCMethod()``;
``FDCAblation('pool', 'qstar', 'r4')`` is numerically identical to the r4 ``QFCMethod()``.
"""
from __future__ import annotations

import math

import numpy as np

from .b4_bal import balanced_alloc
from .frontier_common import QFCMethod

__all__ = ["FDCMethod", "FDCAblation", "fdc_ledger", "union_size", "LEDGERS", "FDC_DELTA", "FDC_SHARE",
           "FACTORIAL_CELLS"]

FDC_DELTA = 0.05
FDC_SHARE = 0.5
# (delta_main, delta_var, C_var); C_var None = S * A computed from the ctx.
LEDGERS = {"r4": (0.04, 0.01, 48), "r5": (0.045, 0.005, None)}
FACTORIAL_CELLS = tuple((d, u, l) for d in ("pool", "half") for u in ("qstar", "feas") for l in ("r4", "r5"))
_DELTA_TOL = 1e-12


def union_size(ctx, union):
    """Number of (q, pi) direction objects per checkpoint in the main union."""
    if union == "feas":
        return int(np.asarray(ctx.feas).sum())                 # sum_q |Pi_{B_q}|, counted exactly
    if union == "qstar":
        return int(ctx.Q * ctx.P)                              # Q * |Pi_all| (r4 Q*-union)
    raise ValueError(f"union must be 'qstar' or 'feas', got {union!r}")


def fdc_ledger(ctx, union="feas", ledger="r5", K=None):
    """Ledger from the ctx only. Returns beta (= L1), x_v and the bookkeeping that proves the delta split.

    K defaults to the number of certificate checkpoints in the ctx (the union over k is over these checkpoints).
    """
    if ledger not in LEDGERS:
        raise ValueError(f"ledger must be one of {sorted(LEDGERS)}, got {ledger!r}")
    d_main, d_var, c_var = LEDGERS[ledger]
    Kc = int(len(ctx.checkpoints)) if K is None else int(K)
    SA = int(ctx.S * ctx.A)
    C = SA if c_var is None else int(c_var)
    m = union_size(ctx, union)
    if union == "qstar" and ctx.P == ctx.A ** ctx.S:
        from ..certify.quadknap import l1_qstar
        beta = l1_qstar(ctx.S, ctx.A, ctx.Q, Kc, d_main)       # same float expression as r4 qfc_default_params
    else:
        beta = math.log(m * Kc / d_main)
    x_v = math.log(2 * C * Kc / d_var)                        # same expression as r4 qfc_default_params
    return {"union": union, "ledger": ledger, "union_size": m, "K": Kc, "C_var": C, "S_A": SA,
            "delta_main": d_main, "delta_var": d_var, "delta_total": d_main + d_var, "beta": beta, "L1": beta,
            "x_v": x_v, "bound_main": m * Kc * math.exp(-beta), "bound_var": 2 * C * Kc * math.exp(-x_v),
            "per_q_feasible": np.asarray(ctx.feas).sum(1).astype(int).tolist(),
            "C_var_covers_cells": bool(C >= SA)}


def _check_feasibility_consistency(ctx):
    """The certificate re-derives Pi_{B_q} (quadknap._feasible); it must equal ctx.feas, which the ledger counts."""
    from ..certify.quadknap import _feasible
    for q, p in enumerate(ctx.problems):
        f, _ = _feasible(ctx.pols, ctx.w, p)
        if not np.array_equal(f, np.asarray(ctx.feas[q], dtype=bool)):
            raise AssertionError(f"feasible class of problem {q} differs between ctx and certificate")


class _FDCBase(QFCMethod):
    """Shared setup: design matrix + ledger from ctx; certificate inherited unchanged from QFCMethod.certify."""

    _design = "half"
    _union = "feas"
    _ledger = "r5"
    _share = FDC_SHARE
    _K_override = None
    _beta_override = None
    _x_v_override = None

    def _base_init(self, name):
        self.name = name
        self.alloc_kind = "pool" if self._design == "pool" else "fixed"
        self.alloc_p = None
        self.params = None
        self.ledger_info = None

    def setup(self, ctx):
        _check_feasibility_consistency(ctx)
        led = fdc_ledger(ctx, self._union, self._ledger, K=self._K_override)
        params = {"L1": led["beta"], "x_v": led["x_v"], "delta_main": led["delta_main"],
                  "delta_var": led["delta_var"], "C_var": led["C_var"], "K": led["K"],
                  "union": self._union, "union_size": led["union_size"], "ledger": self._ledger}
        if self._beta_override is not None:
            params["L1"] = float(self._beta_override)
        if self._x_v_override is not None:
            params["x_v"] = float(self._x_v_override)
        self.params = params
        self.ledger_info = led
        self.alloc_p = None if self._design == "pool" else balanced_alloc(ctx.S, ctx.A, self._share)
        if hasattr(self, "_idx"):
            del self._idx                                      # pols index map is per ctx
        self._post_setup(ctx, led)

    def _post_setup(self, ctx, led):
        pass

    def describe(self):
        d = super().describe()
        d.update({"design": self._design, "union": self._union, "ledger_name": self._ledger,
                  "share_control": None if self._design == "pool" else self._share,
                  "certificate": "quadknap.qfc_certificate_enum (Lemma L1) + make_stats (Lemma L2 inversion)",
                  "ledger": self.ledger_info})
        return d


class FDCMethod(_FDCBase):
    """The FDC method (methodology s2). No constructor arguments: no beta / x_v / share / delta / K override."""

    name = "FDC"
    validity = "rigorous"

    def __init__(self):
        self._base_init("FDC")

    def _post_setup(self, ctx, led):
        if abs(float(ctx.delta) - FDC_DELTA) > _DELTA_TOL:
            raise ValueError(f"FDC ledger is frozen at delta = {FDC_DELTA} (0.045 + 0.005); ctx.delta = {ctx.delta}")
        if ctx.A != 2:
            raise ValueError("FDC is specified for A = 2 (control / treatment 0.5 / 0.5)")
        assert abs(led["delta_total"] - FDC_DELTA) < _DELTA_TOL
        assert abs(led["bound_main"] - led["delta_main"]) < 1e-9 and abs(led["bound_var"] - led["delta_var"]) < 1e-9


class FDCAblation(_FDCBase):
    """C4 factorial / T1 reconciliation cell. Ledger-legal cells are rigorous; other overrides -> 'none' + '-explore'.

    design: 'pool' | 'half';  union: 'qstar' | 'feas';  ledger: 'r4' | 'r5';
    share: control share for design 'half' (None = 0.5; any other value is exploratory);
    K_override: union size over checkpoints (>= number of checkpoints is conservative and legal; smaller is not);
    beta_override / x_v_override: constant exponents (never ledger-legal; exploratory only).
    """

    def __init__(self, design="half", union="feas", ledger="r5", share=None, K_override=None, beta_override=None,
                 x_v_override=None, name=None):
        if design not in ("pool", "half"):
            raise ValueError(f"design must be 'pool' or 'half', got {design!r}")
        if union not in ("qstar", "feas"):
            raise ValueError(f"union must be 'qstar' or 'feas', got {union!r}")
        if ledger not in LEDGERS:
            raise ValueError(f"ledger must be one of {sorted(LEDGERS)}, got {ledger!r}")
        if share is not None and design == "pool":
            raise ValueError("share applies only to design 'half'")
        self._design, self._union, self._ledger = design, union, ledger
        self._share = FDC_SHARE if share is None else float(share)
        self._K_override = None if K_override is None else int(K_override)
        self._beta_override = beta_override
        self._x_v_override = x_v_override
        self._explore_reasons = []
        if share is not None and abs(self._share - FDC_SHARE) > _DELTA_TOL:
            self._explore_reasons.append(f"share={self._share:g}")
        if beta_override is not None:
            self._explore_reasons.append(f"beta={float(beta_override):g}")
        if x_v_override is not None:
            self._explore_reasons.append(f"x_v={float(x_v_override):g}")
        base = name or f"FDCx[{design},{union},{ledger}]"
        self._base_name = base
        self.validity = "rigorous" if not self._explore_reasons else "none"
        self._base_init(base if self.validity == "rigorous" else base + "-explore")

    def _post_setup(self, ctx, led):
        reasons = list(self._explore_reasons)
        Kc = int(len(ctx.checkpoints))
        if self._K_override is not None and self._K_override < Kc:
            reasons.append(f"K_override={self._K_override}<K={Kc}")
        if not led["C_var_covers_cells"]:
            reasons.append(f"C_var={led['C_var']}<S*A={led['S_A']}")
        if abs(float(ctx.delta) - led["delta_total"]) > _DELTA_TOL:
            reasons.append(f"ledger delta {led['delta_total']:g} != ctx.delta {float(ctx.delta):g}")
        self.explore_reasons = reasons
        if reasons:
            self.validity = "none"
            self.name = self._base_name + "-explore"
        else:
            self.validity = "rigorous"
            self.name = self._base_name

    def describe(self):
        d = super().describe()
        d["explore_reasons"] = getattr(self, "explore_reasons", self._explore_reasons)
        return d
